# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(507, 681)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(160, 10, 160, 240))
        self.image.setText("")
        self.image.setObjectName("image")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(150, 250, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(200, 300, 221, 16))
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 330, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.author = QtWidgets.QLabel(Form)
        self.author.setGeometry(QtCore.QRect(190, 390, 161, 16))
        self.author.setObjectName("author")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 420, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.year = QtWidgets.QLabel(Form)
        self.year.setGeometry(QtCore.QRect(190, 480, 161, 16))
        self.year.setObjectName("year")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 500, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.genre = QtWidgets.QLabel(Form)
        self.genre.setGeometry(QtCore.QRect(190, 560, 141, 16))
        self.genre.setObjectName("genre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Книга"))
        self.label.setText(_translate("Form", "Название"))
        self.title.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "Автор"))
        self.author.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "Год выпуска"))
        self.year.setText(_translate("Form", "TextLabel"))
        self.label_4.setText(_translate("Form", "Жанр"))
        self.genre.setText(_translate("Form", "TextLabel"))
